name: Kernel Deployment

env:
  token: ${{ secrets.TOKEN }}
  chat_id: ${{ secrets.CHAT_ID }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kernel_deploy:
    name: Kernel Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container:
      image: nexgang/ubuntu:latest
      options: --cpus 4 --memory 16g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_ENV

      - name: Run Kernel Build Script
        run: bash kernel_build.sh
